# Utilisation de l'image de base Python 3.9
FROM python:3.12.2
RUN python -m pip install --upgrade pip
RUN pip install fastapi uvicorn
RUN pip install https://files.pythonhosted.org/packages/e2/1c/1f2190287fa7fc49ef636c276335e039de379097fb1e712b39e6be44f863/crewai-0.28.8.tar.gz
# Définition du répertoire de travail dans le conteneur
WORKDIR /code

# Copie du fichier requirements.txt dans le répertoire de travail
COPY ./requirements.txt /code/requirements.txt

# Installation des dépendances à partir du fichier requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copie du dossier app dans le répertoire de travail
COPY ./app /code/app

# Exposition du port 80
EXPOSE 89

# Commande pour démarrer l'application avec Uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "89"]
